# Numpy

Numpy è un modulo che gestisce e manipola array di numeri.

Permette di svolgere operazioni tra tutti gli elementi con una sola istruzione facendo risparmiare molte linee di codice. In questo modo lo stile del codice eviterà diversi *loop* uno dentro l'altro favorendo una scrittura più lineare ed in genere fornisce implementazioni più veloci.

A differenze delle liste python, **il tipo di dati è fisso** in numpy perché usa aree di memoria contigue. Questo rende l'implementazione più rapida delle liste usuali. 

* <a href="https://numpy.org/">documentazione</a>

* <a href="https://youtu.be/GB9ByFAIAH4">tutorial online</a>

In [1]:
import numpy as np
import math

In [2]:
x = np.array([2, 5, 6])
y = np.array([3, 7, 8])
xy = x+y
print(xy)

[ 5 12 14]


Definiamo una matrice di rotazione di un angolo $\theta = \pi/3$:

In [3]:
theta = math.pi/3
st = math.sin(theta); ct = math.cos(theta)
rot = np.array([[ct, st],[-st, ct]])
print(rot)
print("dimensions: ", rot.ndim)
print("rows, cols: ", rot.shape)
print("data type: ", rot.dtype)

[[ 0.5        0.8660254]
 [-0.8660254  0.5      ]]
dimensions:  2
rows, cols:  (2, 2)
data type:  float64


In [4]:
rot11 = rot[0,0]; rot12 = rot[0,1]
rot21 = rot[1,0]; rot22 = rot[1,1]
print(rot11, rot12)
print(rot21, rot22)

0.5000000000000001 0.8660254037844386
-0.8660254037844386 0.5000000000000001


Il tipo dei dati può essere specificato come parametro al momento della creazione dell'array.

In [5]:
x = np.array([2, 5, 6], np.int32)
print(x)

[2 5 6]


In [6]:
x = np.array([2, 5, 6], np.float64)
print(x)

[2. 5. 6.]


Accesso alle specifiche righe:

In [7]:
print(rot[0])
print(rot[1])
print(rot[0, :])
print(rot[1, :])

[0.5       0.8660254]
[-0.8660254  0.5      ]
[0.5       0.8660254]
[-0.8660254  0.5      ]


Accesso alle specifiche colonne:

In [8]:
print(rot[:, 0])
print(rot[:, 1])

[ 0.5       -0.8660254]
[0.8660254 0.5      ]


Accesso a sottoinsiemi della matrice (ossia al *minore* della matrice).
Notare: l'ultimo indice in ```1:3``` non è incluso!

In [9]:
m = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10 , 11, 12]])
print(m)
m1 = m[1:3, 1:3]
print(m1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7]
 [10 11]]


Accesso agli elementi saltandone un certo numero

In [10]:
m = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10 , 11, 12, 13, 14, 15, 16]])
print(m)
# skip even or odd columns 
me = m[0:2, 0:8:2]
mo = m[0:2, 1:8:2]
print(me)
print(mo)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  3  5  7]
 [ 9 11 13 15]]
[[ 2  4  6  8]
 [10 12 14 16]]


Accesso ad elementi dato un insieme di indici

Accesso a sottoinsiemi in scrittura:

In [11]:
x = np.zeros(10)
print(x)
x[2:5] = 2
print(x)
x[2:5] = [1, 2, 3]
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 2. 2. 2. 0. 0. 0. 0. 0.]
[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


Inizializzazione: tutti zeri o uno, o non inizializzati

In [12]:
x = np.ones((3,2))
print(x)
x = np.zeros((3,2))
print(x)
x = np.empty((6,8))
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 4.67808622e-310  0.00000000e+000  6.98853958e+228  2.11653524e+214
   9.62006198e+228  3.38460673e+125  6.69053866e+151  6.56693077e-085]
 [ 4.42828483e-239  3.27748881e-313  7.52744116e+252  5.82392120e+252
   6.58203621e-085  1.42800637e+248  9.06343082e+231  7.72198486e+228]
 [ 4.71526669e+180  1.24590723e-224  1.19776716e-312  7.52744116e+252
   5.82392120e+252  2.06934482e+243  1.05632950e-310  2.24261886e-205]
 [ 4.76288587e-313  7.52744116e+252  5.82392120e+252  6.58203139e-085
   3.94354960e+180 -3.38460686e+125  2.57153710e+151  1.50107583e+164]
 [ 5.18763613e-313  3.67767335e-308  1.33360302e+241  2.52305300e-310
   3.79519126e-080  5.54041819e+228  6.75635367e-312  1.27594635e-303]
 [ 3.36312407e-284  1.27613549e-303  5.48092443e-294  8.20430627e-304
   8.20430627e-304  8.20430627e-304  5.74115043e-183  6.95335594e-308]]


Inizializzazione: tutti valori uguali

In [13]:
x = np.full((2,3),3.14)
print(x)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]]


Inizializzazione: casuale

In [14]:
r = np.random.rand(3,3)
print(r)

[[0.75717101 0.11841172 0.44864463]
 [0.49855303 0.61018019 0.82605433]
 [0.43299691 0.37123665 0.77204799]]


Matrice identità

In [15]:
i = np.identity(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Accesso a blocchi in scrittura

In [16]:
i[2:4,0:2] = rot
print(i)

[[ 1.         0.         0.         0.       ]
 [ 0.         1.         0.         0.       ]
 [ 0.5        0.8660254  1.         0.       ]
 [-0.8660254  0.5        0.         1.       ]]


In [17]:
i[0:2,2:4] = rot
print(i)

[[ 1.         0.         0.5        0.8660254]
 [ 0.         1.        -0.8660254  0.5      ]
 [ 0.5        0.8660254  1.         0.       ]
 [-0.8660254  0.5        0.         1.       ]]


Selezione di elementi multipli in base ad un insieme di indici:

In [18]:
x = np.array([10, 20, 30, 40, 50, 60, 70, 80])
ev = x[[1, 3, 5, 7]]
od = x[[0, 2, 4, 6]]
print(ev)
print(od)
x = np.array([[0, 10, 20, 30, 40, 50, 60]])
np.take(x, [2, 3, 5])

[20 40 60 80]
[10 30 50 70]


array([20, 30, 50])

In [19]:
m = np.array([[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 3, 0], [0, 0, 0, 4]])
print(m)
diag = m[[0, 1, 2, 3], [0, 1, 2, 3]]
print(diag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 2 3 4]


# Copie: shallow vs deep
La copia di default è *shallow*, ossia viene assegnato un puntatore all'oggetto originale. Per avere una copia diversa dall'ogetto originale bisogna usare il metodo ```copy()```.

In [20]:
a = np.zeros(5)
b = a
print(a, b)
a[2] = 9
b[3] = 2
print(a,b)

[0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]
[0. 0. 9. 2. 0.] [0. 0. 9. 2. 0.]


In [21]:
a = np.zeros(5)
b = a.copy()
print(a, b)
a[2] = 9
b[3] = 2
print(a,b)

[0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]
[0. 0. 9. 0. 0.] [0. 0. 0. 2. 0.]


# Manipolazione con operazioni matematiche

In sostanza, tutte le operazioni vengono svolte elemento per elemento.

Attenzione! La moltiplicazione tra matrici su puà fare come ```np.matmul(a,b)```, **non** come ```a*b```.

In [22]:
a = np.array([1,2,3])
b = a*2
print(a, b)

[1 2 3] [2 4 6]


Moltiplicazione elemento per elento

In [23]:
a = np.array([1,2,3,4]); b = np.array([3, 4, 5, 6])
ab = a*b
print(a, b, ab)

[1 2 3 4] [3 4 5 6] [ 3  8 15 24]


In [24]:
a6 = a**6
print(a, a6)

[1 2 3 4] [   1   64  729 4096]


Sequenza equispaziata tra un valore minimo ed un valore massimo

In [25]:
bins = 10
theta = np.linspace(0, math.pi, bins)
print(theta)
theta = np.linspace(0, math.pi, 11)
print(theta)

[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]
[0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265]


Possiamo calcolare i valori di una funzione corrispondenti agli elementi che passiamo.

Questa funzione è estremamente utile per fare grafici di una funzione, che di fatto sono curve che passano per una serie di punti forniti dall'utente.

In [26]:
ct = np.cos(theta)
st = np.sin(theta)
np.set_printoptions(precision=4, suppress=True)
print(ct)
print(st)

[ 1.      0.9511  0.809   0.5878  0.309   0.     -0.309  -0.5878 -0.809
 -0.9511 -1.    ]
[0.     0.309  0.5878 0.809  0.9511 1.     0.9511 0.809  0.5878 0.309
 0.    ]


Applicare ripetutamente una funzione. Questa possibilità sfrutta il fatto che python è un interprete. Purché sia definito l'operatore ```**``` (```x**2```), la funzione ```fun``` può essere eseguita.

In [27]:
v = np.array([1, 2, 3, 4, 5])
fun = lambda x: x**2 - 1
#def fun(x): return x**2 -1
f = fun(v)
print(f)

[ 0  3  8 15 24]


Si può definire una funzione che prende come argomento un ```np.array``` e applica ripetutamente un'altra funzione data a ciascun elemento.

In [28]:
def sinus(x):
    return math.sin(x)+math.cos(x)

In [29]:
%%script python --no-raise-error
# l'istruzione che segue dà un errore
f = sinus(v)

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'sinus' is not defined


In [30]:
vfunc = np.vectorize(sinus)
f = vfunc(v)
print(f)

[ 1.3818  0.4932 -0.8489 -1.4104 -0.6753]


In [31]:
def vsinus(x):
    return np.sin(x)+np.cos(x)
f = vsinus(v)
print(f)

[ 1.3818  0.4932 -0.8489 -1.4104 -0.6753]


In [32]:
v = np.array([0.0, 0.1, 0.2, 0.3])
fun = lambda x: 1.0 if x==0 else math.sin(x)/x
f = np.vectorize(fun)(v)
print(f)

[1.     0.9983 0.9933 0.9851]


# Algebra lineare

Prodotto tra matrici

In [33]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[1,2], [3, 4], [5,6]])
ab = np.matmul(a,b)
print(ab)

[[22 28]
 [49 64]]


Determinante

In [34]:
det = np.linalg.det(ab)
print(det)
print(22*64-28*49)

35.99999999999982
36


Matrice inversa

In [35]:
inv = np.linalg.inv(ab)
print(inv)

[[ 1.7778 -0.7778]
 [-1.3611  0.6111]]


Calcolo degli autovalori ed autovettori

In [36]:
a = np.array([[1, 2, 0, 0],[2, 1, 0, 0], [0, 0, 2, 3],[0, 0, 3, 2]])
print(a)

[[1 2 0 0]
 [2 1 0 0]
 [0 0 2 3]
 [0 0 3 2]]


In [37]:
w, v = np.linalg.eig(a)
print(w)
print(v)

[ 3. -1.  5. -1.]
[[ 0.7071 -0.7071  0.      0.    ]
 [ 0.7071  0.7071  0.      0.    ]
 [ 0.      0.      0.7071 -0.7071]
 [ 0.      0.      0.7071  0.7071]]


# Principali indicatori statistici

In seguito daremo una più precisa definizione degli indicatori statistici. Quella che segue è solo un'anteprima.

In [38]:
x = np.random.rand(10)
print(x.min(),x.max())
print("sum: ", x.sum())
print("mean: ", x.sum()/x.shape[0])
print("mean: ", x.mean())
print("mean sq: ", (x**2).mean())
print("variance: ", (x**2).mean()-x.mean()**2)
print("variance: ", x.var())
print("std. dev: ", math.sqrt(x.var()))
print("std. dev: ", x.std())

0.035965159311319383 0.8978241001288835
sum:  4.448288563682131
mean:  0.4448288563682131
mean:  0.4448288563682131
mean sq:  0.2840225622335991
variance:  0.08614985077574674
variance:  0.08614985077574669
std. dev:  0.2935129482250258
std. dev:  0.2935129482250258


In [39]:
m = np.random.rand(6, 4)
print(m)
print("sum: ", m.sum())
print("sum cols: ", m.sum(axis = 0))
print("sum rows: ", m.sum(axis = 1))

[[0.4736 0.985  0.6671 0.728 ]
 [0.3533 0.7319 0.4411 0.4425]
 [0.7713 0.2547 0.6654 0.0095]
 [0.6395 0.9239 0.1664 0.3007]
 [0.6139 0.3743 0.5883 0.158 ]
 [0.3753 0.8448 0.8611 0.9353]]
sum:  13.304685553511737
sum cols:  [3.2268 4.1146 3.3893 2.5739]
sum rows:  [2.8537 1.9687 1.7009 2.0305 1.7344 3.0165]


# Altre manipolazioni

In [40]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v = np.vstack([v1,v2])
print(v)

[[1 2 3 4]
 [5 6 7 8]]


In [41]:
h1 = np.array([[1,2], [3, 4]])
h2 = np.array([[5, 6, 7], [8, 9, 10]])
h = np.hstack([h1, h2])
print(h)

[[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


Non è una funzione ```numpy```, ma è un modo comodo per iterare contemporaneamente su due o più array:

In [42]:
v = zip(v1, v2)
print(v)
for a, b in zip(v1, v2):
    print(a, b)

1 5
2 6
3 7
4 8


# Input da file
I numeri sono di default interpretati come float

In [43]:
m = np.genfromtxt('data/np-data.txt', delimiter=',')
print(m)
m = m.astype('int32')
print(m)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Condizioni booleane

In [44]:
(m > 3)

array([[False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [45]:
((m > 3) & (m < 7))

array([[False, False],
       [False,  True],
       [ True,  True],
       [False, False]])

Selezione degli elementi secondo una condizione

In [46]:
x = np.random.rand(10)
print(x)
print(x>0.5)
x1 = x[x>0.5]
print(x1)

[0.6156 0.3613 0.4342 0.3414 0.3009 0.3615 0.7282 0.7416 0.1453 0.9849]
[ True False False False False False  True  True False  True]
[0.6156 0.7282 0.7416 0.9849]
