# Numpy

Numpy è un modulo che gestisce e manipola array di numeri.

Permette di svolgere operazioni tra tutti gli elementi con una sola istruzione facendo risparmiare molte linee di codice. In questo modo lo stile del codice eviterà diversi *loop* uno dentro l'altro favorendo una scrittura più lineare ed in genere fornisce implementazioni più veloci.

A differenze delle liste python, **il tipo di dati è fisso** in numpy perché usa aree di memoria contigue. Questo rende l'implementazione più rapida delle liste usuali. 

* <a href="https://numpy.org/">documentazione</a>

* <a href="https://youtu.be/GB9ByFAIAH4">tutorial online</a>

In [1]:
import numpy as np
import math

In [2]:
x = np.array([2, 5, 6])
y = np.array([3, 7, 8])
xy = x+y
print(xy)

[ 5 12 14]


Definiamo una matrice di rotazione di un angolo $\theta = \pi/3$:

In [3]:
theta = math.pi/3
st = math.sin(theta); ct = math.cos(theta)
rot = np.array([[ct, st],[-st, ct]])
print(rot)
print("dimensions: ", rot.ndim)
print("rows, cols: ", rot.shape)
print("data type: ", rot.dtype)

[[ 0.5        0.8660254]
 [-0.8660254  0.5      ]]
dimensions:  2
rows, cols:  (2, 2)
data type:  float64


In [4]:
rot11 = rot[0,0]; rot12 = rot[0,1]
rot21 = rot[1,0]; rot22 = rot[1,1]
print(rot11, rot12)
print(rot21, rot22)

0.5000000000000001 0.8660254037844386
-0.8660254037844386 0.5000000000000001


Il tipo dei dati può essere specificato come parametro al momento della creazione dell'array.

In [5]:
x = np.array([2, 5, 6], np.int32)
print(x)

[2 5 6]


In [6]:
x = np.array([2, 5, 6], np.float64)
print(x)

[2. 5. 6.]


Accesso alle specifiche righe:

In [7]:
print(rot[0])
print(rot[1])
print(rot[0, :])
print(rot[1, :])

[0.5       0.8660254]
[-0.8660254  0.5      ]
[0.5       0.8660254]
[-0.8660254  0.5      ]


Accesso alle specifiche colonne:

In [8]:
print(rot[:, 0])
print(rot[:, 1])

[ 0.5       -0.8660254]
[0.8660254 0.5      ]


Accesso a sottoinsiemi della matrice (ossia al *minore* della matrice).
Notare: l'ultimo indice in ```1:3``` non è incluso!

In [9]:
m = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10 , 11, 12]])
print(m)
m1 = m[1:3, 1:3]
print(m1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7]
 [10 11]]


Accesso agli elementi saltandone un certo numero

In [10]:
m = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10 , 11, 12, 13, 14, 15, 16]])
print(m)
# skip even or odd columns 
me = m[0:2, 0:8:2]
mo = m[0:2, 1:8:2]
print(me)
print(mo)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  3  5  7]
 [ 9 11 13 15]]
[[ 2  4  6  8]
 [10 12 14 16]]


Accesso ad elementi dato un insieme di indici

In [11]:
x = np.array([[0, 10, 20, 30, 40, 50, 60]])
np.take(x, [2, 3, 5])

array([20, 30, 50])

Accesso a sottoinsiemi in scrittura:

In [12]:
x = np.zeros(10)
print(x)
x[2:5] = 2
print(x)
x[2:5] = [1, 2, 3]
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 2. 2. 2. 0. 0. 0. 0. 0.]
[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


Inizializzazione: tutti zeri o uno

In [13]:
x = np.zeros((3,2))
print(x)
x = np.ones((3,2))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


Inizializzazione: tutti valori uguali

In [14]:
x = np.full((2,3),2)
print(x)

[[2 2 2]
 [2 2 2]]


Inizializzazione: casuale

In [15]:
r = np.random.rand(3,3)
print(r)

[[0.18414716 0.93286349 0.22007916]
 [0.90427978 0.94694394 0.98676434]
 [0.35206755 0.73197697 0.92714874]]


Matrice identità

In [16]:
i = np.identity(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Accesso a blocchi in scrittura

In [17]:
i[2:4,0:2] = rot
print(i)

[[ 1.         0.         0.         0.       ]
 [ 0.         1.         0.         0.       ]
 [ 0.5        0.8660254  1.         0.       ]
 [-0.8660254  0.5        0.         1.       ]]


In [18]:
i[0:2,2:4] = rot
print(i)

[[ 1.         0.         0.5        0.8660254]
 [ 0.         1.        -0.8660254  0.5      ]
 [ 0.5        0.8660254  1.         0.       ]
 [-0.8660254  0.5        0.         1.       ]]


Selezione di elementi multipli in base ad un insieme di indici:

In [19]:
x = np.array([10, 20, 30, 40, 50, 60, 70, 80])
ev = x[[1, 3, 5, 7]]
od = x[[0, 2, 4, 6]]
print(ev)
print(od)

[20 40 60 80]
[10 30 50 70]


In [20]:
m = np.array([[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 3, 0], [0, 0, 0, 4]])
print(m)
diag = m[[0, 1, 2, 3], [0, 1, 2, 3]]
print(diag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 2 3 4]


# Copie: shallow vs deep
La copia di default è *shallow*, ossia viene assegnato un puntatore all'oggetto originale. Per avere una copia diversa dall'ogetto originale bisogna usare il metodo ```copy()```.

In [21]:
a = np.zeros(5)
b = a
print(a, b)
a[2] = 9
print(a,b)

[0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]
[0. 0. 9. 0. 0.] [0. 0. 9. 0. 0.]


In [22]:
a = np.zeros(5)
b = a.copy()
print(a, b)
a[2] = 9
b[3] = 2
print(a,b)

[0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]
[0. 0. 9. 0. 0.] [0. 0. 0. 2. 0.]


# Manipolazione con operazioni matematiche

In sostanza, tutte le operazioni vengono svolte elemento per elemento.

Attenzione! La moltiplicazione tra matrici su puà fare come ```np.matmul(a,b)```, **non** come ```a*b```.

In [23]:
a = np.array([1,2,3])
b = a*2
print(a, b)

[1 2 3] [2 4 6]


Moltiplicazione elemento per elento

In [24]:
a = np.array([1,2,3,4]); b = np.array([3, 4, 5, 6])
ab = a*b
print(a, b, ab)

[1 2 3 4] [3 4 5 6] [ 3  8 15 24]


In [25]:
a2 = a**6
print(a, a2)

[1 2 3 4] [   1   64  729 4096]


Sequenza equispaziata tra un valore minimo ed un valore massimo

In [26]:
bins = 10
step = math.pi/bins
theta = np.arange(0, math.pi+0.00001, step)
print(theta)

[0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265]


Possiamo calcolare i valori di una funzione corrispondenti agli elementi che passiamo.

Questa funzione è estremamente utile per fare grafici di una funzione, che di fatto sono curve che passano per una serie di punti forniti dall'utente.

In [27]:
ct = np.cos(theta)
st = np.sin(theta)
np.set_printoptions(precision=4, suppress=True)
print(ct)
print(st)

[ 1.      0.9511  0.809   0.5878  0.309   0.     -0.309  -0.5878 -0.809
 -0.9511 -1.    ]
[0.     0.309  0.5878 0.809  0.9511 1.     0.9511 0.809  0.5878 0.309
 0.    ]


Applicare ripetutamente una funzione. Questa possibilità sfrutta il fatto che python è un interprete. Purché sia definito l'operatore ```**``` (```x**2```), la funzione ```fun``` può essere eseguita.

In [28]:
v = np.array([1, 2, 3, 4, 5])
fun = lambda x: x**2 - 1
f = fun(v)
print(f)

[ 0  3  8 15 24]


Si può definire una funzione che prende come argomento un ```np.array``` e applica ripetutamente un'altra funzione data a ciascun elemento.

In [29]:
def sinus(x):
    return math.sin(x)+math.cos(x)

In [30]:
# l'istruzione che segue dà un errore
f = sinus(x)

TypeError: only size-1 arrays can be converted to Python scalars

In [31]:
vfunc = np.vectorize(sinus)
f = vfunc(v)
print(f)

[ 1.3818  0.4932 -0.8489 -1.4104 -0.6753]


In [32]:
v = np.array([0.0, 0.1, 0.2, 0.3])
fun = lambda x: 1.0 if x==0 else math.sin(x)/x
f = np.vectorize(fun)(v)
print(f)

[1.     0.9983 0.9933 0.9851]


# Algebra lineare

Prodotto tra matrici

In [33]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[1,2], [3, 4], [5,6]])
ab = np.matmul(a,b)
print(ab)

[[22 28]
 [49 64]]


Determinante

In [34]:
det = np.linalg.det(ab)
print(det)
print(22*64-28*49)

35.99999999999982
36


Matrice inversa

In [35]:
inv = np.linalg.inv(ab)
print(inv)

[[ 1.7778 -0.7778]
 [-1.3611  0.6111]]


Calcolo degli autovalori ed autovettori

In [36]:
a = np.array([[1, 2, 0, 0],[2, 1, 0, 0], [0, 0, 2, 3],[0, 0, 3, 2]])
print(a)

[[1 2 0 0]
 [2 1 0 0]
 [0 0 2 3]
 [0 0 3 2]]


In [37]:
w, v = np.linalg.eig(a)
print(w)
print(v)

[ 3. -1.  5. -1.]
[[ 0.7071 -0.7071  0.      0.    ]
 [ 0.7071  0.7071  0.      0.    ]
 [ 0.      0.      0.7071 -0.7071]
 [ 0.      0.      0.7071  0.7071]]


# Principali indicatori statistici

In seguito daremo una più precisa definizione degli indicatori statistici. Quella che segue è solo un'anteprima.

In [38]:
x = np.random.rand(10)
print(x.min(),x.max())
print("sum: ", x.sum())
print("mean: ", x.sum()/x.shape[0])
print("mean: ", x.mean())
print("mean sq: ", (x**2).mean())
print("variance: ", (x**2).mean()-x.mean()**2)
print("variance: ", x.var())
print("std. dev: ", math.sqrt(x.var()))
print("std. dev: ", x.std())

0.32730737516809516 0.9737051249065672
sum:  5.7861062912552
mean:  0.57861062912552
mean:  0.57861062912552
mean sq:  0.3859624608927989
variance:  0.05117220075576889
variance:  0.051172200755769025
std. dev:  0.2262127334076688
std. dev:  0.2262127334076688


In [39]:
m = np.random.rand(6, 4)
print(m)
print("sum: ", m.sum())
print("sum cols: ", m.sum(axis = 0))
print("sum rows: ", m.sum(axis = 1))

[[0.6051 0.8988 0.4336 0.6488]
 [0.7023 0.0483 0.7959 0.6827]
 [0.3236 0.8288 0.0726 0.2266]
 [0.4992 0.3059 0.0733 0.7056]
 [0.9881 0.8126 0.9574 0.6519]
 [0.621  0.5575 0.8544 0.3217]]
sum:  13.615804905614226
sum cols:  [3.7393 3.4519 3.1873 3.2373]
sum rows:  [2.5863 2.2292 1.4516 1.5841 3.41   2.3546]


# Altre manipolazioni

In [40]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v = np.vstack([v1,v2])
print(v)

[[1 2 3 4]
 [5 6 7 8]]


In [41]:
h1 = np.array([[1,2], [3, 4]])
h2 = np.array([[5, 6, 7], [8, 9, 10]])
h = np.hstack([h1, h2])
print(h)

[[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


Non è una funzione ```numpy```, ma è un modo comodo per iterare contemporaneamente su due o più array:

In [42]:
v = zip(v1,v2)
print(v)
for a, b in zip(v1, v2):
    print(a, b)

1 5
2 6
3 7
4 8


# Input da file
I numeri sono di default interpretati come float

In [44]:
m = np.genfromtxt('data/np-data.txt', delimiter=',')
print(m)
m = m.astype('int32')
print(m)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Condizioni booleane

In [45]:
(m > 3)

array([[False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [46]:
((m > 3) & (m < 7))

array([[False, False],
       [False,  True],
       [ True,  True],
       [False, False]])

Selezione degli elementi secondo una condizione

In [47]:
x = np.random.rand(10)
x1 = x[x>0.5]
print(x)
print(x1)

[0.0604 0.1407 0.8184 0.3367 0.073  0.6342 0.2351 0.007  0.1117 0.9925]
[0.8184 0.6342 0.9925]
